# Generated by Django 3.2.12 on 2022-03-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLastIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.CharField(blank=True, max_length=64, null=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
